### ISSUE TITLE
cyrillic encoding

### ISSUE THREAD

**Issue by kostadinoff** [quarto-dev/quarto-gallery#2]
I love the gallery, however in R studio i can not reproduce the Tufte's template when i'm using cyrillic alphabet in the text. Can that be fixed somehow?

**Comment by dragonstyle** [comment]
Thanks for the kind words. Quarto defaults to using `xelatex` to compile LaTeX to PDF, so things should generally work. One common issue might be the font selection (and in particular whether the font includes cyrillic characters).  I was able to compile the Tufte template as follows by providing a new font (note `mainfont` under the `pdf` key):


```
---
title: "A Quarto Page Layout Example"
subtitle: "Inspired by Tufte Handout, Using Quarto"
date: last-modified
format:
  pdf:
    mainfont: Arial
  html: 
    self-contained: true
reference-location: margin
citation-location: margin
bibliography: skeleton.bib
---

# Introduction

Этот документ демонстрирует использование ряда этих функций макета страницы для создания привлекательного и удобного документа, вдохновленного стилем раздаточного материала Tufte и использованием стилей Tufte в документах RMarkdown [@xie2018]. Стиль раздаточных материалов Тафте — это стиль, который Эдвард Тафте использует в своих книгах и раздаточных материалах. Стиль Тафте известен широким использованием боковых примечаний, тесной интеграцией графики с текстом и хорошо подобранной типографикой. Quarto[^1] поддерживает большинство методов компоновки, которые используются в стиле раздаточных материалов Tufte для вывода как HTML, так и LaTeX/PDF.

[^1]: To learn more, you can read more about [Quarto](https://www.quarto.org) or visit [Quarto's Github repository](https://www.github.com/quarto-dev/quarto-cli).
```

I hope that this helps. If not, please give me a little more information about the error that you're seeing, including hopefully  a way that I can reproduce it.
