### ISSUE TITLE
Setting papersize to A4 breaks Tufte margin 

### ISSUE THREAD

**Issue by ramiromagno** [quarto-dev/quarto-gallery#7]
Setting:

```yaml
format:
    pdf:
      keep-tex: true
      papersize: A4
```

Results in:

![a4](https://github.com/quarto-dev/quarto-gallery/assets/19862384/feef641e-9ff4-4790-bf6a-c8a5ef3e696f)

**Comment by ramiromagno** [comment]
Seemingly, with `letter` this line is added to the tex file:

```tex
\usepackage[left=1in,marginparwidth=2.0666666666667in,textwidth=4.1333333333333in,marginparsep=0.3in]{geometry}
```

but not if:

```yaml
format:
    pdf:
      keep-tex: true
      papersize: A4
```

I manually fixed the tex by adding geometry package and it rendered with a nice Tufte margin. :) So this seems like a bug.

**Comment by NeubertJonas** [comment]
Thanks for highlighting this issue @ramiromagno. In case somebody else is wondering how to manually add the geometry package, here is what works for me. (There might be a more elegant solution, I'm no expert in LaTex.)

For the document YAML
````yaml
format:
    pdf:
      template-partials:
        - doc-class.tex
        - before-title.tex
````

doc-class.tex
````latex
\documentclass[
  a4paper,
  DIV=11,
  numbers=noendperiod,
  oneside]{scrartcl}
````

before-title.tex
````latex
\usepackage[left=1in,marginparwidth=2.0666666666667in,textwidth=4.1333333333333in,marginparsep=0.3in]{geometry}
````

For some reason, using only the before-title.tex and specifying A4 in the YAML will change the document class (i.e., using {article} instead of {scrartcl} and leaving out the DIV and numbers parameters) and, thus, not render the document correctly.
